name: MacOS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: master

      - name: Setup Gyro
        uses: mattnite/setup-gyro@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        run: gyro build test

      - name: Setup Package
        working-directory: examples
        run: gyro redirect --alias zfetch --path ..

      - name: Example (Get)
        working-directory: examples
        run: gyro build run-get

      - name: Example (Post)
        working-directory: examples
        run: gyro build run-post

      - name: Example (Download)
        working-directory: examples
        run: gyro build run-download

      - name: Example (Evented)
        working-directory: examples
        run: gyro build run-evented
